create table public.membership_content_texts (
  id bigint generated by default as identity primary key,
  text_key text not null unique,
  text_value text not null,
  updated_at timestamptz not null default now(),
  updated_by uuid not null default auth.uid() references auth.users (id),
  constraint membership_content_texts_key_format
    check (text_key ~ '^[A-Za-z0-9_-]{1,160}$'),
  constraint membership_content_texts_value_length
    check (char_length(text_value) <= 10000)
);

create index membership_content_texts_updated_by_idx
  on public.membership_content_texts (updated_by);

alter table public.membership_content_texts enable row level security;

grant select on public.membership_content_texts to anon, authenticated;
grant insert, update, delete on public.membership_content_texts to authenticated;
grant usage, select on sequence public.membership_content_texts_id_seq to authenticated;

create policy "Public can read membership content text"
on public.membership_content_texts
for select
to anon, authenticated
using (true);

create policy "Thumbnail admins can insert membership content text"
on public.membership_content_texts
for insert
to authenticated
with check (
  (select public.is_membership_thumbnail_admin())
  and updated_by = (select auth.uid())
);

create policy "Thumbnail admins can update membership content text"
on public.membership_content_texts
for update
to authenticated
using ((select public.is_membership_thumbnail_admin()))
with check (
  (select public.is_membership_thumbnail_admin())
  and updated_by = (select auth.uid())
);

create policy "Thumbnail admins can delete membership content text"
on public.membership_content_texts
for delete
to authenticated
using ((select public.is_membership_thumbnail_admin()));

insert into public.membership_content_texts (
  text_key,
  text_value,
  updated_by
)
select seeded.text_key, seeded.text_value, users.id
from (
  values
    ('tx-4', '교육부 추천 미래 교육'),
    ('tx-22', '믿고 보는 콘텐츠'),
    ('tx-23', '교육부 미래 교육 실천을 위한 필수 콘텐츠를 한곳에 모았어요.'),
    ('tx-138', '세계문화'),
    ('tx-17', '명화 갤러리')
) as seeded(text_key, text_value)
join auth.users as users
  on lower(users.email) = 'wjddms945@gmail.com'
on conflict (text_key) do update
set
  text_value = excluded.text_value,
  updated_by = excluded.updated_by,
  updated_at = now();
