create table public.membership_content_thumbnails (
  id bigint generated by default as identity primary key,
  content_key text not null unique,
  image_url text not null,
  storage_path text,
  updated_at timestamptz not null default now(),
  updated_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  constraint membership_content_thumbnails_content_key_format
    check (content_key ~ '^[a-z0-9][a-z0-9-]{1,119}$'),
  constraint membership_content_thumbnails_image_url_https
    check (image_url ~ '^https://')
);

alter table public.membership_content_thumbnails enable row level security;

grant select on public.membership_content_thumbnails to anon, authenticated;
grant insert, update, delete on public.membership_content_thumbnails to authenticated;
grant usage, select on sequence public.membership_content_thumbnails_id_seq to authenticated;

create policy "Public can read membership thumbnails"
on public.membership_content_thumbnails
for select
to anon, authenticated
using (true);

create policy "Thumbnail admins can insert membership thumbnails"
on public.membership_content_thumbnails
for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and (select auth.jwt() -> 'app_metadata' ->> 'membership_thumbnail_admin') = 'true'
  and updated_by = (select auth.uid())
);

create policy "Thumbnail admins can update membership thumbnails"
on public.membership_content_thumbnails
for update
to authenticated
using (
  (select auth.jwt() -> 'app_metadata' ->> 'membership_thumbnail_admin') = 'true'
)
with check (
  (select auth.jwt() -> 'app_metadata' ->> 'membership_thumbnail_admin') = 'true'
  and updated_by = (select auth.uid())
);

create policy "Thumbnail admins can delete membership thumbnails"
on public.membership_content_thumbnails
for delete
to authenticated
using (
  (select auth.jwt() -> 'app_metadata' ->> 'membership_thumbnail_admin') = 'true'
);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'membership-thumbnails',
  'membership-thumbnails',
  true,
  5242880,
  array['image/webp', 'image/jpeg', 'image/png']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Thumbnail admins can upload membership images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'membership-thumbnails'
  and (select auth.jwt() -> 'app_metadata' ->> 'membership_thumbnail_admin') = 'true'
  and lower(storage.extension(name)) in ('webp', 'jpg', 'jpeg', 'png')
);

create policy "Thumbnail admins can delete membership images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'membership-thumbnails'
  and (select auth.jwt() -> 'app_metadata' ->> 'membership_thumbnail_admin') = 'true'
);
